export const archiveCopy = {
  ru: {
    title: "Истории и идеи сообщества Sabat.",
    intro: "Рассказываем о проектах Sabat, людях и идеях, которые помогают знаниям приносить пользу обществу. Делимся опытом участников и результатами важных инициатив.",
    latest: "Последние публикации",
    read: "Читать материал",
    imageLabel: "Фото материала",
    back: "Все новости",
    previous: "Предыдущая новость",
    next: "Следующая новость",
  },
  ky: {
    title: "Sabat коомчулугунун баяндары жана идеялары.",
    intro: "Sabat долбоорлору, адамдар жана билимди коомдун пайдасына багыттаган идеялар жөнүндө айтып беребиз. Катышуучулардын тажрыйбасын жана маанилүү демилгелердин жыйынтыктарын бөлүшөбүз.",
    latest: "Акыркы жарыялар",
    read: "Материалды окуу",
    imageLabel: "Материалдын сүрөтү",
    back: "Бардык жаңылыктар",
    previous: "Мурунку жаңылык",
    next: "Кийинки жаңылык",
  },
  en: {
    title: "Stories and ideas from the Sabat community.",
    intro: "Stories about Sabat projects, people and ideas that help knowledge create value for society. We share participants’ experiences and the results of meaningful initiatives.",
    latest: "Latest stories",
    read: "Read the story",
    imageLabel: "Story image",
    back: "All news",
    previous: "Previous story",
    next: "Next story",
  },
};
