export const archiveCopy = {
  ru: {
    title: 'Истории и идеи Общественного фонда "Сабат".',
    intro: 'Рассказываем о проектах Общественного фонда "Сабат", людях и идеях, которые помогают знаниям приносить пользу обществу. Делимся опытом участников и результатами важных инициатив.',
    latest: "Последние публикации",
    read: "Читать материал",
    imageLabel: "Фото материала",
    back: "Все новости",
    previous: "Предыдущая новость",
    next: "Следующая новость",
  },
  ky: {
    title: '\"Сабат\" коомдук фонду: баяндар жана идеялар.',
    intro: '\"Сабат\" коомдук фонду ишке ашырган долбоорлор, адамдар жана билимди коомдун пайдасына багыттаган идеялар жөнүндө айтып беребиз. Катышуучулардын тажрыйбасын жана маанилүү демилгелердин жыйынтыктарын бөлүшөбүз.',
    latest: "Акыркы жарыялар",
    read: "Материалды окуу",
    imageLabel: "Материалдын сүрөтү",
    back: "Бардык жаңылыктар",
    previous: "Мурунку жаңылык",
    next: "Кийинки жаңылык",
  },
  en: {
    title: "Stories and ideas from Sabat Public Foundation.",
    intro: "Stories about Sabat Public Foundation projects, people and ideas that help knowledge create value for society. We share participants’ experiences and the results of meaningful initiatives.",
    latest: "Latest stories",
    read: "Read the story",
    imageLabel: "Story image",
    back: "All news",
    previous: "Previous story",
    next: "Next story",
  },
};
