export const archiveCopy = {
  ru: {
    title: "События, истории и идеи сообщества Sabat.",
    intro: "Рассказываем о проектах фонда, людях, которые их создают, и практиках, помогающих знаниям приносить пользу обществу.",
    latest: "Последние публикации",
    read: "Читать материал",
    imageLabel: "Фото материала",
    back: "Все новости",
    previous: "Предыдущая новость",
    next: "Следующая новость",
  },
  ky: {
    title: "Sabat коомчулугунун окуялары, баяндары жана идеялары.",
    intro: "Фонддун долбоорлору, аларды түзгөн адамдар жана билимди коомдун пайдасына багыттаган тажрыйбалар жөнүндө айтып беребиз.",
    latest: "Акыркы жарыялар",
    read: "Материалды окуу",
    imageLabel: "Материалдын сүрөтү",
    back: "Бардык жаңылыктар",
    previous: "Мурунку жаңылык",
    next: "Кийинки жаңылык",
  },
  en: {
    title: "Stories, events and ideas from the Sabat community.",
    intro: "Updates on the foundation’s projects, the people behind them and the practices that help knowledge create value for society.",
    latest: "Latest stories",
    read: "Read the story",
    imageLabel: "Story image",
    back: "All news",
    previous: "Previous story",
    next: "Next story",
  },
};
