import type { Language, NewsPage } from "../lib/api";

// Keep the public news area useful while the editorial API wakes up. The
// client refreshes this snapshot in the background as soon as the page loads.
export const fallbackNews: Record<Language, NewsPage> = {
  ru: {
    items: [
      {
        id: "fb5fc405-c4b9-4ee9-82d2-a555fbaa9580",
        slug: "new-season",
        category: "Инициативы",
        author: null,
        coverImageUrl: null,
        title: "Новый сезон общественных проектов Sabat",
        excerpt: "Запускаем встречи, открытые площадки и новые форматы совместной работы.",
        publishedAt: "2026-06-18T09:00:00+00:00",
      },
      {
        id: "12016208-e515-443f-bc20-5ae3abf47d20",
        slug: "community-meeting",
        category: "События",
        author: null,
        coverImageUrl: null,
        title: "Открытая встреча сообщества Sabat",
        excerpt: "Участники обсудили идеи, которые могут улучшить жизнь вокруг нас.",
        publishedAt: "2026-06-04T09:00:00+00:00",
      },
      {
        id: "dd227d62-3cdb-4931-a5e1-f9a8a7094e84",
        slug: "small-steps",
        category: "Истории",
        author: null,
        coverImageUrl: null,
        title: "Почему большие перемены начинаются с малого",
        excerpt: "Пять простых принципов, которые помогают инициативе стать устойчивой.",
        publishedAt: "2026-05-22T09:00:00+00:00",
      },
      {
        id: "e8f34e16-2ede-49ca-b231-43edd4ebb176",
        slug: "partners",
        category: "Партнёрство",
        author: null,
        coverImageUrl: null,
        title: "Sabat открыт к новым партнёрствам",
        excerpt: "Приглашаем организации, экспертов и активных людей создавать полезные проекты вместе.",
        publishedAt: "2026-05-08T09:00:00+00:00",
      },
    ],
    page: 1,
    pageSize: 12,
    totalCount: 4,
    totalPages: 1,
  },
  ky: {
    items: [
      {
        id: "fb5fc405-c4b9-4ee9-82d2-a555fbaa9580",
        slug: "new-season",
        category: "Демилгелер",
        author: null,
        coverImageUrl: null,
        title: "Sabat коомдук долбоорлорунун жаңы сезону",
        excerpt: "Жолугушууларды, ачык аянтчаларды жана биргелешкен иштин жаңы форматтарын баштайбыз.",
        publishedAt: "2026-06-18T09:00:00+00:00",
      },
      {
        id: "12016208-e515-443f-bc20-5ae3abf47d20",
        slug: "community-meeting",
        category: "Окуялар",
        author: null,
        coverImageUrl: null,
        title: "Sabat коомчулугунун ачык жолугушуусу",
        excerpt: "Катышуучулар айланабыздагы жашоону жакшырта турган идеяларды талкуулашты.",
        publishedAt: "2026-06-04T09:00:00+00:00",
      },
      {
        id: "dd227d62-3cdb-4931-a5e1-f9a8a7094e84",
        slug: "small-steps",
        category: "Баяндар",
        author: null,
        coverImageUrl: null,
        title: "Эмне үчүн чоң өзгөрүүлөр кичине кадамдардан башталат",
        excerpt: "Демилгенин туруктуу болушуна жардам берген беш жөнөкөй принцип.",
        publishedAt: "2026-05-22T09:00:00+00:00",
      },
      {
        id: "e8f34e16-2ede-49ca-b231-43edd4ebb176",
        slug: "partners",
        category: "Өнөктөштүк",
        author: null,
        coverImageUrl: null,
        title: "Sabat жаңы өнөктөштүккө ачык",
        excerpt: "Уюмдарды, эксперттерди жана активдүү адамдарды пайдалуу долбоорлорду чогуу түзүүгө чакырабыз.",
        publishedAt: "2026-05-08T09:00:00+00:00",
      },
    ],
    page: 1,
    pageSize: 12,
    totalCount: 4,
    totalPages: 1,
  },
  en: {
    items: [
      {
        id: "fb5fc405-c4b9-4ee9-82d2-a555fbaa9580",
        slug: "new-season",
        category: "Initiatives",
        author: null,
        coverImageUrl: null,
        title: "A new season of Sabat community projects",
        excerpt: "New meetings, open platforms and formats for working together are about to begin.",
        publishedAt: "2026-06-18T09:00:00+00:00",
      },
      {
        id: "12016208-e515-443f-bc20-5ae3abf47d20",
        slug: "community-meeting",
        category: "Events",
        author: null,
        coverImageUrl: null,
        title: "An open meeting of the Sabat community",
        excerpt: "Participants discussed ideas that can improve everyday life around us.",
        publishedAt: "2026-06-04T09:00:00+00:00",
      },
      {
        id: "dd227d62-3cdb-4931-a5e1-f9a8a7094e84",
        slug: "small-steps",
        category: "Stories",
        author: null,
        coverImageUrl: null,
        title: "Why meaningful change begins with small steps",
        excerpt: "Five simple principles that help an initiative become sustainable.",
        publishedAt: "2026-05-22T09:00:00+00:00",
      },
      {
        id: "e8f34e16-2ede-49ca-b231-43edd4ebb176",
        slug: "partners",
        category: "Partnerships",
        author: null,
        coverImageUrl: null,
        title: "Sabat is open to new partnerships",
        excerpt: "We invite organisations, experts and active citizens to create useful projects together.",
        publishedAt: "2026-05-08T09:00:00+00:00",
      },
    ],
    page: 1,
    pageSize: 12,
    totalCount: 4,
    totalPages: 1,
  },
};
